name: forcemirrors
description: A mirrors helper library for the dart force framework
version: 0.1.2+1
author: Joris Hermans <hermansj@gmail.com>
homepage: https://github.com/jorishermans/dart-forcemvc
dependencies:
  unittest: '>=0.9.0 <0.9.1'
