name: forcemirrors
description: A mirrors helper library
version: 0.2.1+2
author: Joris Hermans <hermansj@gmail.com>
homepage: https://github.com/ForceUniverse/dart-forcemirrors
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'
